name: torch-latest
channels:
  - pytorch-nightly
  - nvidia
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blas=2.119=mkl
  - blas-devel=3.9.0=19_win64_mkl
  - brotli-python=1.1.0=py310h00ffb61_1
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.7.22=h56e8100_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cuda-cccl=12.3.52=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.52=0
  - cuda-opencl-dev=12.3.52=0
  - cuda-profiler-api=12.3.52=0
  - cuda-runtime=12.1.0=0
  - filelock=3.13.1=pyhd8ed1ab_0
  - freetype=2.12.1=hdaf720e_2
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2023.2.0=h57928b3_50497
  - jinja2=3.1.2=pyhd8ed1ab_1
  - lcms2=2.15=h67d730c_3
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=19_win64_mkl
  - libcblas=3.9.0=19_win64_mkl
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.4.52=0
  - libcurand-dev=10.3.4.52=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.19=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libhwloc=2.9.3=default_haede6df_1009
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=19_win64_mkl
  - liblapacke=3.9.0=19_win64_mkl
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h19919ed_0
  - libsqlite=3.44.0=hcfcfb64_0
  - libtiff=4.6.0=h6e2ebb7_2
  - libuv=1.44.2=hcfcfb64_1
  - libwebp-base=1.3.2=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.11.5=hc3477c8_1
  - libzlib=1.2.13=hcfcfb64_5
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.3=py310h8d17308_1
  - mkl=2023.2.0=h6a75c08_50496
  - mkl-devel=2023.2.0=h57928b3_50496
  - mkl-include=2023.2.0=h6a75c08_50496
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.0=py310hf667824_0
  - openjpeg=2.5.0=h3d672ee_3
  - openssl=3.1.4=hcfcfb64_0
  - pillow=10.1.0=py310h1e6a543_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.13=h4de0772_0_cpython
  - python_abi=3.10=4_cp310
  - pytorch=2.2.0.dev20231104=py3.10_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h8d17308_1
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tbb=2021.10.0=h91493d7_2
  - tk=8.6.13=hcfcfb64_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hdcecf7f_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wheel=0.41.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zstd=1.5.5=h12be248_0
  - pip:
      - accelerate==0.24.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - cffi==1.16.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - diffusers==0.23.1
      - distro==1.8.0
      - fonttools==4.44.0
      - fsspec==2023.10.0
      - gensim==4.3.2
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.25.1
      - huggingface-hub==0.17.3
      - importlib-metadata==6.8.0
      - kiwisolver==1.4.5
      - matplotlib==3.8.1
      - openai==1.3.5
      - protobuf==4.25.0
      - pycparser==2.21
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pyparsing==3.1.1
      - python-dotenv==1.0.0
      - regex==2023.10.3
      - safetensors==0.4.0
      - scipy==1.11.4
      - sentencepiece==0.1.99
      - smart-open==6.4.0
      - sniffio==1.3.0
      - sounddevice==0.4.6
      - tokenizers==0.14.1
      - torchaudio==2.2.0.dev20231104
      - torchvision==0.17.0.dev20231104
      - tqdm==4.66.1
      - transformers==4.35.0
      - wave==0.0.2
      - zipp==3.17.0
